---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: monitoring
    box: ubuntu/bionic64
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      interpreter_python: auto
      deprecation_warnings: false
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlPersist=6000s -o ControlMaster=auto -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
